Jacob Kickbush
Homework 1
Python for Data Analysis

Import numpy to use it's functions, and use the np.random.rand function to create a 2x3 array of random numbers between 0 and 1.
Then I print the array, its shape, and its dtype.

In [1]:
import numpy as np

array1 = np.random.rand(2,3)

print(array1)
print(array1.shape)
print(array1.dtype)

[[0.95383303 0.68707407 0.88148523]
 [0.72893147 0.21431709 0.91699753]]
(2, 3)
float64


Add 1 to every value in the array and overwrite the previous array with the new one.

In [2]:
array1 = array1 + 1

print(array1)

[[1.95383303 1.68707407 1.88148523]
 [1.72893147 1.21431709 1.91699753]]


Multiply the array by the list [10,20,30] meaning each row of 3 numbers will be multiplied by each one respectively.

In [3]:
array1 = array1 * [10,20,30]

print(array1)

[[19.53833034 33.74148136 56.44455676]
 [17.28931474 24.28634181 57.50992578]]


Here I overwrote the first row of the array by indexing array1[0] and changed the values for that row to 22. 

In [4]:
array1[0] = 22

print(array1)

[[22.         22.         22.        ]
 [17.28931474 24.28634181 57.50992578]]


I created two new arrays, both 1x10 with random numbers between 0 and 1. I then made a 4th array that was the difference of these two arrays. 

In [5]:
array2 = np.random.rand(1,10)
array3 = np.random.rand(1,10)

print(array2)
print()
print(array3)
print()

array4 = array3 - array2

print(array4)

[[0.35217376 0.83543489 0.22416949 0.89462002 0.13100761 0.78048855
  0.40109143 0.42918124 0.7454878  0.76909069]]

[[0.28822049 0.55006845 0.19500692 0.98786714 0.5797507  0.14959333
  0.9086949  0.00732248 0.67082072 0.51037537]]

[[-0.06395327 -0.28536644 -0.02916257  0.09324712  0.44874309 -0.63089521
   0.50760347 -0.42185876 -0.07466708 -0.25871533]]


Used the .mean() method on the array to get the mean. Used np.median and np.std to get the median and standard deviation of the array.

In [6]:
print(array4.mean())
print(np.median(array4))
print(np.std(array4))

-0.07150249813670333
-0.06931017287846497
0.3393342678665559


Used boolean indexing to print out every number in the array4 if that number was greater than 0.2

In [7]:
print(array4[array4 > .2])

[0.44874309 0.50760347]
